spring:
  datasource:
    url: jdbc:h2:file:./data/desafiosantander;MODE=PostgreSQL;;INIT=CREATE SCHEMA IF NOT EXISTS santander
    driver-class-name: org.h2.Driver
    username: desafio
    password:
    schema: santander
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  cache:
    type: caffeine
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
